version: '3.7'
services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo_pass
      - POSTGRES_USER=odoo
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    
  odoo:
    image: odoo:17.0 
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      # mount folder custom_addons & config file
      - ./custom_addons:/mnt/extra-addons 
      - ./odoo.conf:/etc/odoo/odoo.conf
    # run Odoo with specific config file
    command: --config=/etc/odoo/odoo.conf
    environment:
      # database connection for Odoo
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo_pass

volumes:
  db-data: